#!/bin/bash
##########################################################
#     Automatically generated by the PandA framework     #
##########################################################

# Synthesis script for COMPONENT: add_float_top

#configuration
. /opt/Xilinx/Vivado/2022.2/settings64.sh >& /dev/null; 

# STEP: vivado_flow
cd /home/nghielme/PycharmProjects/thesis-project/addmul/add_float
ulimit -s 131072; vivado -mode batch -nojournal -nolog -source /home/nghielme/PycharmProjects/thesis-project/addmul/add_float/HLS_output//Synthesis/vivado_flow/vivado.tcl


