-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity add_fixed_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a : IN STD_LOGIC_VECTOR (319 downto 0);
    b : IN STD_LOGIC_VECTOR (319 downto 0);
    res : OUT STD_LOGIC_VECTOR (319 downto 0);
    res_ap_vld : OUT STD_LOGIC );
end;


architecture behav of add_fixed_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "add_fixed_top_add_fixed_top,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=50.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=33.353750,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=309,HLS_SYN_LUT=1053,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_118 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal add_ln1334_fu_247_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_reg_653 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_4_fu_295_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_4_reg_658 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_8_fu_343_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_8_reg_663 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_12_fu_391_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_12_reg_668 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_16_fu_439_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_16_reg_673 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_20_fu_487_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_20_reg_678 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_24_fu_535_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_24_reg_683 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_28_fu_583_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_28_reg_688 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_693 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1309_1_reg_698 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln1309_2_reg_703 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln1356_fu_85_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1358_fu_159_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1334_1_fu_237_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_fu_233_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal l_fu_241_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal l_1_fu_253_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1356_1_fu_89_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1358_1_fu_163_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1334_3_fu_269_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_2_fu_265_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln1334_2_fu_277_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_16_fu_261_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_17_fu_273_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_5_fu_289_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_2_fu_283_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal l_3_fu_301_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1356_2_fu_99_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1358_2_fu_173_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1334_5_fu_317_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_4_fu_313_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln1334_6_fu_325_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_18_fu_309_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_19_fu_321_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_9_fu_337_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_4_fu_331_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal l_5_fu_349_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1356_3_fu_109_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1358_3_fu_183_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1334_7_fu_365_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_6_fu_361_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln1334_10_fu_373_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_20_fu_357_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_21_fu_369_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_13_fu_385_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_6_fu_379_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal l_7_fu_397_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1356_4_fu_119_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1358_4_fu_193_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1334_9_fu_413_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_8_fu_409_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln1334_14_fu_421_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_22_fu_405_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_23_fu_417_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_17_fu_433_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_8_fu_427_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal l_9_fu_445_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1356_5_fu_129_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1358_5_fu_203_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1334_11_fu_461_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_10_fu_457_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln1334_18_fu_469_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_24_fu_453_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_25_fu_465_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_21_fu_481_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_10_fu_475_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal l_11_fu_493_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1356_6_fu_139_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1358_6_fu_213_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1334_13_fu_509_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_12_fu_505_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln1334_22_fu_517_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_26_fu_501_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_27_fu_513_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_25_fu_529_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_12_fu_523_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal l_13_fu_541_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1356_7_fu_149_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1358_7_fu_223_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1334_15_fu_557_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_14_fu_553_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln1334_26_fu_565_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_28_fu_549_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln1334_29_fu_561_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln1334_29_fu_577_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal l_14_fu_571_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln479_fu_617_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln479_1_fu_620_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal add_ln479_fu_625_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_i_fu_630_p10 : STD_LOGIC_VECTOR (280 downto 0);
    signal sext_ln6_fu_644_p1 : STD_LOGIC_VECTOR (287 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln1334_12_reg_668 <= add_ln1334_12_fu_391_p2;
                add_ln1334_16_reg_673 <= add_ln1334_16_fu_439_p2;
                add_ln1334_20_reg_678 <= add_ln1334_20_fu_487_p2;
                add_ln1334_24_reg_683 <= add_ln1334_24_fu_535_p2;
                add_ln1334_28_reg_688 <= add_ln1334_28_fu_583_p2;
                add_ln1334_4_reg_658 <= add_ln1334_4_fu_295_p2;
                add_ln1334_8_reg_663 <= add_ln1334_8_fu_343_p2;
                add_ln1334_reg_653 <= add_ln1334_fu_247_p2;
                tmp_reg_693 <= l_14_fu_571_p2(32 downto 32);
                trunc_ln1309_1_reg_698 <= a(280 downto 256);
                trunc_ln1309_2_reg_703 <= b(280 downto 256);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln1334_10_fu_373_p2 <= std_logic_vector(unsigned(zext_ln1334_7_fu_365_p1) + unsigned(zext_ln1334_6_fu_361_p1));
    add_ln1334_12_fu_391_p2 <= std_logic_vector(unsigned(add_ln1334_13_fu_385_p2) + unsigned(trunc_ln1358_3_fu_183_p4));
    add_ln1334_13_fu_385_p2 <= std_logic_vector(unsigned(trunc_ln1356_3_fu_109_p4) + unsigned(zext_ln1334_21_fu_369_p1));
    add_ln1334_14_fu_421_p2 <= std_logic_vector(unsigned(zext_ln1334_9_fu_413_p1) + unsigned(zext_ln1334_8_fu_409_p1));
    add_ln1334_16_fu_439_p2 <= std_logic_vector(unsigned(add_ln1334_17_fu_433_p2) + unsigned(trunc_ln1358_4_fu_193_p4));
    add_ln1334_17_fu_433_p2 <= std_logic_vector(unsigned(trunc_ln1356_4_fu_119_p4) + unsigned(zext_ln1334_23_fu_417_p1));
    add_ln1334_18_fu_469_p2 <= std_logic_vector(unsigned(zext_ln1334_11_fu_461_p1) + unsigned(zext_ln1334_10_fu_457_p1));
    add_ln1334_20_fu_487_p2 <= std_logic_vector(unsigned(add_ln1334_21_fu_481_p2) + unsigned(trunc_ln1358_5_fu_203_p4));
    add_ln1334_21_fu_481_p2 <= std_logic_vector(unsigned(trunc_ln1356_5_fu_129_p4) + unsigned(zext_ln1334_25_fu_465_p1));
    add_ln1334_22_fu_517_p2 <= std_logic_vector(unsigned(zext_ln1334_13_fu_509_p1) + unsigned(zext_ln1334_12_fu_505_p1));
    add_ln1334_24_fu_535_p2 <= std_logic_vector(unsigned(add_ln1334_25_fu_529_p2) + unsigned(trunc_ln1358_6_fu_213_p4));
    add_ln1334_25_fu_529_p2 <= std_logic_vector(unsigned(trunc_ln1356_6_fu_139_p4) + unsigned(zext_ln1334_27_fu_513_p1));
    add_ln1334_26_fu_565_p2 <= std_logic_vector(unsigned(zext_ln1334_15_fu_557_p1) + unsigned(zext_ln1334_14_fu_553_p1));
    add_ln1334_28_fu_583_p2 <= std_logic_vector(unsigned(add_ln1334_29_fu_577_p2) + unsigned(trunc_ln1358_7_fu_223_p4));
    add_ln1334_29_fu_577_p2 <= std_logic_vector(unsigned(trunc_ln1356_7_fu_149_p4) + unsigned(zext_ln1334_29_fu_561_p1));
    add_ln1334_2_fu_277_p2 <= std_logic_vector(unsigned(zext_ln1334_3_fu_269_p1) + unsigned(zext_ln1334_2_fu_265_p1));
    add_ln1334_4_fu_295_p2 <= std_logic_vector(unsigned(add_ln1334_5_fu_289_p2) + unsigned(trunc_ln1358_1_fu_163_p4));
    add_ln1334_5_fu_289_p2 <= std_logic_vector(unsigned(trunc_ln1356_1_fu_89_p4) + unsigned(zext_ln1334_17_fu_273_p1));
    add_ln1334_6_fu_325_p2 <= std_logic_vector(unsigned(zext_ln1334_5_fu_317_p1) + unsigned(zext_ln1334_4_fu_313_p1));
    add_ln1334_8_fu_343_p2 <= std_logic_vector(unsigned(add_ln1334_9_fu_337_p2) + unsigned(trunc_ln1358_2_fu_173_p4));
    add_ln1334_9_fu_337_p2 <= std_logic_vector(unsigned(trunc_ln1356_2_fu_99_p4) + unsigned(zext_ln1334_19_fu_321_p1));
    add_ln1334_fu_247_p2 <= std_logic_vector(unsigned(trunc_ln1358_fu_159_p1) + unsigned(trunc_ln1356_fu_85_p1));
    add_ln479_1_fu_620_p2 <= std_logic_vector(unsigned(trunc_ln1309_1_reg_698) + unsigned(zext_ln479_fu_617_p1));
    add_ln479_fu_625_p2 <= std_logic_vector(unsigned(add_ln479_1_fu_620_p2) + unsigned(trunc_ln1309_2_reg_703));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    l_10_fu_475_p2 <= std_logic_vector(unsigned(add_ln1334_18_fu_469_p2) + unsigned(zext_ln1334_24_fu_453_p1));
    l_11_fu_493_p3 <= l_10_fu_475_p2(32 downto 32);
    l_12_fu_523_p2 <= std_logic_vector(unsigned(add_ln1334_22_fu_517_p2) + unsigned(zext_ln1334_26_fu_501_p1));
    l_13_fu_541_p3 <= l_12_fu_523_p2(32 downto 32);
    l_14_fu_571_p2 <= std_logic_vector(unsigned(add_ln1334_26_fu_565_p2) + unsigned(zext_ln1334_28_fu_549_p1));
    l_1_fu_253_p3 <= l_fu_241_p2(32 downto 32);
    l_2_fu_283_p2 <= std_logic_vector(unsigned(add_ln1334_2_fu_277_p2) + unsigned(zext_ln1334_16_fu_261_p1));
    l_3_fu_301_p3 <= l_2_fu_283_p2(32 downto 32);
    l_4_fu_331_p2 <= std_logic_vector(unsigned(add_ln1334_6_fu_325_p2) + unsigned(zext_ln1334_18_fu_309_p1));
    l_5_fu_349_p3 <= l_4_fu_331_p2(32 downto 32);
    l_6_fu_379_p2 <= std_logic_vector(unsigned(add_ln1334_10_fu_373_p2) + unsigned(zext_ln1334_20_fu_357_p1));
    l_7_fu_397_p3 <= l_6_fu_379_p2(32 downto 32);
    l_8_fu_427_p2 <= std_logic_vector(unsigned(add_ln1334_14_fu_421_p2) + unsigned(zext_ln1334_22_fu_405_p1));
    l_9_fu_445_p3 <= l_8_fu_427_p2(32 downto 32);
    l_fu_241_p2 <= std_logic_vector(unsigned(zext_ln1334_1_fu_237_p1) + unsigned(zext_ln1334_fu_233_p1));
    res <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln6_fu_644_p1),320));

    res_ap_vld_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            res_ap_vld <= ap_const_logic_1;
        else 
            res_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln6_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_i_fu_630_p10),288));

    tmp_i_fu_630_p10 <= ((((((((add_ln479_fu_625_p2 & add_ln1334_28_reg_688) & add_ln1334_24_reg_683) & add_ln1334_20_reg_678) & add_ln1334_16_reg_673) & add_ln1334_12_reg_668) & add_ln1334_8_reg_663) & add_ln1334_4_reg_658) & add_ln1334_reg_653);
    trunc_ln1356_1_fu_89_p4 <= a(63 downto 32);
    trunc_ln1356_2_fu_99_p4 <= a(95 downto 64);
    trunc_ln1356_3_fu_109_p4 <= a(127 downto 96);
    trunc_ln1356_4_fu_119_p4 <= a(159 downto 128);
    trunc_ln1356_5_fu_129_p4 <= a(191 downto 160);
    trunc_ln1356_6_fu_139_p4 <= a(223 downto 192);
    trunc_ln1356_7_fu_149_p4 <= a(255 downto 224);
    trunc_ln1356_fu_85_p1 <= a(32 - 1 downto 0);
    trunc_ln1358_1_fu_163_p4 <= b(63 downto 32);
    trunc_ln1358_2_fu_173_p4 <= b(95 downto 64);
    trunc_ln1358_3_fu_183_p4 <= b(127 downto 96);
    trunc_ln1358_4_fu_193_p4 <= b(159 downto 128);
    trunc_ln1358_5_fu_203_p4 <= b(191 downto 160);
    trunc_ln1358_6_fu_213_p4 <= b(223 downto 192);
    trunc_ln1358_7_fu_223_p4 <= b(255 downto 224);
    trunc_ln1358_fu_159_p1 <= b(32 - 1 downto 0);
    zext_ln1334_10_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1356_5_fu_129_p4),33));
    zext_ln1334_11_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1358_5_fu_203_p4),33));
    zext_ln1334_12_fu_505_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1356_6_fu_139_p4),33));
    zext_ln1334_13_fu_509_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1358_6_fu_213_p4),33));
    zext_ln1334_14_fu_553_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1356_7_fu_149_p4),33));
    zext_ln1334_15_fu_557_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1358_7_fu_223_p4),33));
    zext_ln1334_16_fu_261_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_1_fu_253_p3),33));
    zext_ln1334_17_fu_273_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_1_fu_253_p3),32));
    zext_ln1334_18_fu_309_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_3_fu_301_p3),33));
    zext_ln1334_19_fu_321_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_3_fu_301_p3),32));
    zext_ln1334_1_fu_237_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1358_fu_159_p1),33));
    zext_ln1334_20_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_5_fu_349_p3),33));
    zext_ln1334_21_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_5_fu_349_p3),32));
    zext_ln1334_22_fu_405_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_7_fu_397_p3),33));
    zext_ln1334_23_fu_417_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_7_fu_397_p3),32));
    zext_ln1334_24_fu_453_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_9_fu_445_p3),33));
    zext_ln1334_25_fu_465_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_9_fu_445_p3),32));
    zext_ln1334_26_fu_501_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_11_fu_493_p3),33));
    zext_ln1334_27_fu_513_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_11_fu_493_p3),32));
    zext_ln1334_28_fu_549_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_13_fu_541_p3),33));
    zext_ln1334_29_fu_561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(l_13_fu_541_p3),32));
    zext_ln1334_2_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1356_1_fu_89_p4),33));
    zext_ln1334_3_fu_269_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1358_1_fu_163_p4),33));
    zext_ln1334_4_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1356_2_fu_99_p4),33));
    zext_ln1334_5_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1358_2_fu_173_p4),33));
    zext_ln1334_6_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1356_3_fu_109_p4),33));
    zext_ln1334_7_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1358_3_fu_183_p4),33));
    zext_ln1334_8_fu_409_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1356_4_fu_119_p4),33));
    zext_ln1334_9_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1358_4_fu_193_p4),33));
    zext_ln1334_fu_233_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1356_fu_85_p1),33));
    zext_ln479_fu_617_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_693),25));
end behav;
