// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fixed_to_float_top_convert_ac_fixed_ac_float_25_2_8_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        from_v_v_read,
        ap_return
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] from_v_v_read;
output  [70:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[70:0] ap_return;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] tab_address0;
reg    tab_ce0;
wire   [2:0] tab_q0;
wire   [31:0] value_fu_172_p1;
reg   [31:0] value_reg_582;
wire   [31:0] value_1_fu_177_p4;
reg   [31:0] value_1_reg_589;
wire   [0:0] retval_fu_194_p2;
reg   [0:0] retval_reg_595;
wire   [0:0] grp_fu_163_p3;
reg   [0:0] ext_sign_reg_599;
wire   [0:0] grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_return;
reg   [0:0] targetBlock_reg_604;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln2118_fu_234_p2;
reg   [0:0] icmp_ln2118_reg_611;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln2122_fu_262_p2;
reg   [0:0] icmp_ln2122_reg_617;
wire   [0:0] icmp_ln2126_fu_286_p2;
reg   [0:0] icmp_ln2126_reg_622;
wire    grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_start;
wire    grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_done;
wire    grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_idle;
wire    grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_ready;
wire   [0:0] grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_k_2_out;
wire    grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_k_2_out_ap_vld;
wire   [31:0] grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_select_ln678_out;
wire    grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_select_ln678_out_ap_vld;
wire   [5:0] add_ln2142_fu_361_p2;
reg   [5:0] ap_phi_mux_phi_ln2142_phi_fu_127_p4;
reg   [5:0] phi_ln2142_reg_123;
wire    ap_CS_fsm_state4;
wire   [63:0] r_v_v_4_fu_510_p3;
reg   [63:0] ap_phi_mux_f_m_v_v_phi_fu_137_p4;
reg   [63:0] f_m_v_v_reg_134;
wire   [6:0] sub15_i_i_i_i_i_op_fu_519_p2;
reg   [6:0] ap_phi_mux_value_6_phi_fu_147_p4;
reg   [6:0] value_6_reg_143;
reg    grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_start_reg;
reg   [0:0] k_2_loc_fu_100;
reg   [31:0] select_ln678_loc_fu_96;
wire   [63:0] zext_ln2130_fu_314_p1;
wire   [31:0] or_ln1034_fu_188_p2;
wire   [31:0] xor_ln2116_fu_206_p2;
wire   [31:0] t_fu_212_p3;
wire   [15:0] t_1_fu_220_p4;
wire   [31:0] zext_ln2118_fu_230_p1;
wire   [31:0] t_2_fu_240_p3;
wire   [23:0] t_3_fu_248_p4;
wire   [31:0] zext_ln2122_fu_258_p1;
wire   [31:0] t_4_fu_268_p3;
wire   [27:0] trunc_ln2_fu_276_p4;
wire   [3:0] tmp_1_fu_292_p4;
wire   [3:0] trunc_ln2126_fu_302_p1;
wire   [3:0] t_5_fu_306_p3;
wire   [4:0] select_ln2118_1_fu_319_p3;
wire   [4:0] select_ln2125_fu_326_p3;
wire   [4:0] select_ln2122_1_fu_333_p3;
wire   [4:0] or_ln2126_fu_340_p2;
wire   [4:0] select_ln2126_1_fu_346_p3;
wire   [5:0] zext_ln2116_fu_353_p1;
wire   [5:0] zext_ln2130_1_fu_357_p1;
wire   [0:0] xor_ln2142_fu_368_p2;
wire   [5:0] shl_ln_fu_373_p3;
wire   [5:0] add_ln609_1_fu_381_p2;
wire   [31:0] shl_ln1_fu_387_p3;
wire   [31:0] add_ln609_fu_395_p2;
wire   [5:0] trunc_ln4_fu_401_p4;
wire   [4:0] s31_fu_415_p4;
wire   [0:0] tmp_4_fu_439_p3;
wire   [31:0] value_8_fu_454_p3;
wire   [31:0] value_7_fu_447_p3;
wire   [5:0] zext_ln1794_1_fu_429_p1;
wire   [5:0] sub10_i_i_i_i_i_i_i_fu_468_p2;
wire   [31:0] zext_ln1794_fu_425_p1;
wire   [31:0] zext_ln1799_fu_474_p1;
wire   [31:0] lshr_ln1799_fu_490_p2;
wire   [31:0] shl_ln1799_fu_484_p2;
wire   [31:0] value_5_fu_496_p2;
wire   [31:0] value_4_fu_478_p2;
wire   [0:0] icmp_ln1796_fu_433_p2;
wire   [63:0] r_v_v_fu_460_p3;
wire   [63:0] r_v_v_1_fu_502_p3;
wire   [6:0] zext_ln3157_fu_411_p1;
wire  signed [24:0] trunc_ln5_fu_526_p4;
wire   [0:0] retval_1_fu_540_p2;
wire   [6:0] select_ln346_fu_546_p3;
wire  signed [31:0] sext_ln609_fu_536_p1;
wire   [70:0] tmp_fu_554_p4;
reg   [70:0] ap_return_preg;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_start_reg = 1'b0;
#0 ap_return_preg = 71'd0;
end

fixed_to_float_top_convert_ac_fixed_ac_float_25_2_8_0_s_tab_ROM_AUTO_1R #(
    .DataWidth( 3 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
tab_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tab_address0),
    .ce0(tab_ce0),
    .q0(tab_q0)
);

fixed_to_float_top_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213 grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_start),
    .ap_done(grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_done),
    .ap_idle(grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_idle),
    .ap_ready(grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_ready),
    .value_1(value_1_reg_589),
    .value_r(value_reg_582),
    .sext_ln2137(ext_sign_reg_599),
    .k_2_out(grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_k_2_out),
    .k_2_out_ap_vld(grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_k_2_out_ap_vld),
    .select_ln678_out(grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_select_ln678_out),
    .select_ln678_out_ap_vld(grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_select_ln678_out_ap_vld),
    .ap_return(grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_preg[0] <= 1'b0;
        ap_return_preg[1] <= 1'b0;
        ap_return_preg[2] <= 1'b0;
        ap_return_preg[3] <= 1'b0;
        ap_return_preg[4] <= 1'b0;
        ap_return_preg[5] <= 1'b0;
        ap_return_preg[6] <= 1'b0;
        ap_return_preg[7] <= 1'b0;
        ap_return_preg[8] <= 1'b0;
        ap_return_preg[9] <= 1'b0;
        ap_return_preg[10] <= 1'b0;
        ap_return_preg[11] <= 1'b0;
        ap_return_preg[12] <= 1'b0;
        ap_return_preg[13] <= 1'b0;
        ap_return_preg[14] <= 1'b0;
        ap_return_preg[15] <= 1'b0;
        ap_return_preg[16] <= 1'b0;
        ap_return_preg[17] <= 1'b0;
        ap_return_preg[18] <= 1'b0;
        ap_return_preg[19] <= 1'b0;
        ap_return_preg[20] <= 1'b0;
        ap_return_preg[21] <= 1'b0;
        ap_return_preg[22] <= 1'b0;
        ap_return_preg[23] <= 1'b0;
        ap_return_preg[24] <= 1'b0;
        ap_return_preg[25] <= 1'b0;
        ap_return_preg[26] <= 1'b0;
        ap_return_preg[27] <= 1'b0;
        ap_return_preg[28] <= 1'b0;
        ap_return_preg[29] <= 1'b0;
        ap_return_preg[30] <= 1'b0;
        ap_return_preg[31] <= 1'b0;
        ap_return_preg[64] <= 1'b0;
        ap_return_preg[65] <= 1'b0;
        ap_return_preg[66] <= 1'b0;
        ap_return_preg[67] <= 1'b0;
        ap_return_preg[68] <= 1'b0;
        ap_return_preg[69] <= 1'b0;
        ap_return_preg[70] <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
                        ap_return_preg[31 : 0] <= tmp_fu_554_p4[31 : 0];
            ap_return_preg[70 : 64] <= tmp_fu_554_p4[70 : 64];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (retval_fu_194_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_start_reg <= 1'b1;
        end else if ((grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_ready == 1'b1)) begin
            grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (retval_fu_194_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        f_m_v_v_reg_134 <= from_v_v_read;
    end else if (((retval_reg_595 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        f_m_v_v_reg_134 <= r_v_v_4_fu_510_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((targetBlock_reg_604 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        phi_ln2142_reg_123 <= 6'd0;
    end else if (((targetBlock_reg_604 == 1'd0) & (retval_reg_595 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        phi_ln2142_reg_123 <= add_ln2142_fu_361_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (retval_fu_194_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        value_6_reg_143 <= 7'd30;
    end else if (((retval_reg_595 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        value_6_reg_143 <= sub15_i_i_i_i_i_op_fu_519_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((retval_fu_194_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        ext_sign_reg_599 <= from_v_v_read[32'd63];
    end
end

always @ (posedge ap_clk) begin
    if (((targetBlock_reg_604 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_ln2118_reg_611 <= icmp_ln2118_fu_234_p2;
        icmp_ln2122_reg_617 <= icmp_ln2122_fu_262_p2;
        icmp_ln2126_reg_622 <= icmp_ln2126_fu_286_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_k_2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        k_2_loc_fu_100 <= grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_k_2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        retval_reg_595 <= retval_fu_194_p2;
        value_1_reg_589 <= {{from_v_v_read[63:32]}};
        value_reg_582 <= value_fu_172_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_select_ln678_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        select_ln678_loc_fu_96 <= grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_select_ln678_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        targetBlock_reg_604 <= grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_return;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((retval_reg_595 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_f_m_v_v_phi_fu_137_p4 = r_v_v_4_fu_510_p3;
    end else begin
        ap_phi_mux_f_m_v_v_phi_fu_137_p4 = f_m_v_v_reg_134;
    end
end

always @ (*) begin
    if (((targetBlock_reg_604 == 1'd0) & (retval_reg_595 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_phi_ln2142_phi_fu_127_p4 = add_ln2142_fu_361_p2;
    end else begin
        ap_phi_mux_phi_ln2142_phi_fu_127_p4 = phi_ln2142_reg_123;
    end
end

always @ (*) begin
    if (((retval_reg_595 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_value_6_phi_fu_147_p4 = sub15_i_i_i_i_i_op_fu_519_p2;
    end else begin
        ap_phi_mux_value_6_phi_fu_147_p4 = value_6_reg_143;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_return = tmp_fu_554_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tab_ce0 = 1'b1;
    end else begin
        tab_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (retval_fu_194_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if (((ap_start == 1'b1) & (retval_fu_194_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln2142_fu_361_p2 = (zext_ln2116_fu_353_p1 + zext_ln2130_1_fu_357_p1);

assign add_ln609_1_fu_381_p2 = (shl_ln_fu_373_p3 + ap_phi_mux_phi_ln2142_phi_fu_127_p4);

assign add_ln609_fu_395_p2 = ($signed(shl_ln1_fu_387_p3) + $signed(32'd4227858432));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_start = grp_convert_ac_fixed_ac_float_25_2_8_0_Pipeline_VITIS_LOOP_213_fu_154_ap_start_reg;

assign grp_fu_163_p3 = from_v_v_read[32'd63];

assign icmp_ln1796_fu_433_p2 = ((s31_fu_415_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln2118_fu_234_p2 = ((t_1_fu_220_p4 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln2122_fu_262_p2 = ((t_3_fu_248_p4 != 24'd0) ? 1'b1 : 1'b0);

assign icmp_ln2126_fu_286_p2 = ((trunc_ln2_fu_276_p4 != 28'd0) ? 1'b1 : 1'b0);

assign lshr_ln1799_fu_490_p2 = value_7_fu_447_p3 >> zext_ln1799_fu_474_p1;

assign or_ln1034_fu_188_p2 = (value_fu_172_p1 | value_1_fu_177_p4);

assign or_ln2126_fu_340_p2 = (select_ln2122_1_fu_333_p3 | 5'd4);

assign r_v_v_1_fu_502_p3 = {{value_5_fu_496_p2}, {value_4_fu_478_p2}};

assign r_v_v_4_fu_510_p3 = ((icmp_ln1796_fu_433_p2[0:0] == 1'b1) ? r_v_v_fu_460_p3 : r_v_v_1_fu_502_p3);

assign r_v_v_fu_460_p3 = {{value_8_fu_454_p3}, {value_7_fu_447_p3}};

assign retval_1_fu_540_p2 = ((trunc_ln5_fu_526_p4 == 25'd0) ? 1'b1 : 1'b0);

assign retval_fu_194_p2 = ((or_ln1034_fu_188_p2 == 32'd0) ? 1'b1 : 1'b0);

assign s31_fu_415_p4 = {{add_ln609_fu_395_p2[30:26]}};

assign select_ln2118_1_fu_319_p3 = ((icmp_ln2118_reg_611[0:0] == 1'b1) ? 5'd0 : 5'd16);

assign select_ln2122_1_fu_333_p3 = ((icmp_ln2122_reg_617[0:0] == 1'b1) ? select_ln2118_1_fu_319_p3 : select_ln2125_fu_326_p3);

assign select_ln2125_fu_326_p3 = ((icmp_ln2118_reg_611[0:0] == 1'b1) ? 5'd8 : 5'd24);

assign select_ln2126_1_fu_346_p3 = ((icmp_ln2126_reg_622[0:0] == 1'b1) ? select_ln2122_1_fu_333_p3 : or_ln2126_fu_340_p2);

assign select_ln346_fu_546_p3 = ((retval_1_fu_540_p2[0:0] == 1'b1) ? 7'd0 : ap_phi_mux_value_6_phi_fu_147_p4);

assign sext_ln609_fu_536_p1 = trunc_ln5_fu_526_p4;

assign shl_ln1799_fu_484_p2 = value_8_fu_454_p3 << zext_ln1794_fu_425_p1;

assign shl_ln1_fu_387_p3 = {{add_ln609_1_fu_381_p2}, {26'd0}};

assign shl_ln_fu_373_p3 = {{xor_ln2142_fu_368_p2}, {5'd0}};

assign sub10_i_i_i_i_i_i_i_fu_468_p2 = ($signed(6'd32) - $signed(zext_ln1794_1_fu_429_p1));

assign sub15_i_i_i_i_i_op_fu_519_p2 = (7'd30 - zext_ln3157_fu_411_p1);

assign t_1_fu_220_p4 = {{t_fu_212_p3[31:16]}};

assign t_2_fu_240_p3 = ((icmp_ln2118_fu_234_p2[0:0] == 1'b1) ? zext_ln2118_fu_230_p1 : t_fu_212_p3);

assign t_3_fu_248_p4 = {{t_2_fu_240_p3[31:8]}};

assign t_4_fu_268_p3 = ((icmp_ln2122_fu_262_p2[0:0] == 1'b1) ? zext_ln2122_fu_258_p1 : t_2_fu_240_p3);

assign t_5_fu_306_p3 = ((icmp_ln2126_fu_286_p2[0:0] == 1'b1) ? tmp_1_fu_292_p4 : trunc_ln2126_fu_302_p1);

assign t_fu_212_p3 = ((grp_fu_163_p3[0:0] == 1'b1) ? xor_ln2116_fu_206_p2 : select_ln678_loc_fu_96);

assign tab_address0 = zext_ln2130_fu_314_p1;

assign tmp_1_fu_292_p4 = {{t_4_fu_268_p3[7:4]}};

assign tmp_4_fu_439_p3 = add_ln609_fu_395_p2[32'd31];

assign tmp_fu_554_p4 = {{{select_ln346_fu_546_p3}, {32'd0}}, {sext_ln609_fu_536_p1}};

assign trunc_ln2126_fu_302_p1 = t_4_fu_268_p3[3:0];

assign trunc_ln2_fu_276_p4 = {{t_4_fu_268_p3[31:4]}};

assign trunc_ln4_fu_401_p4 = {{add_ln609_fu_395_p2[31:26]}};

assign trunc_ln5_fu_526_p4 = {{ap_phi_mux_f_m_v_v_phi_fu_137_p4[63:39]}};

assign value_1_fu_177_p4 = {{from_v_v_read[63:32]}};

assign value_4_fu_478_p2 = value_7_fu_447_p3 << zext_ln1794_fu_425_p1;

assign value_5_fu_496_p2 = (shl_ln1799_fu_484_p2 | lshr_ln1799_fu_490_p2);

assign value_7_fu_447_p3 = ((tmp_4_fu_439_p3[0:0] == 1'b1) ? 32'd0 : value_reg_582);

assign value_8_fu_454_p3 = ((tmp_4_fu_439_p3[0:0] == 1'b1) ? value_reg_582 : value_1_reg_589);

assign value_fu_172_p1 = from_v_v_read[31:0];

assign xor_ln2116_fu_206_p2 = (select_ln678_loc_fu_96 ^ 32'd4294967295);

assign xor_ln2142_fu_368_p2 = (k_2_loc_fu_100 ^ 1'd1);

assign zext_ln1794_1_fu_429_p1 = s31_fu_415_p4;

assign zext_ln1794_fu_425_p1 = s31_fu_415_p4;

assign zext_ln1799_fu_474_p1 = sub10_i_i_i_i_i_i_i_fu_468_p2;

assign zext_ln2116_fu_353_p1 = select_ln2126_1_fu_346_p3;

assign zext_ln2118_fu_230_p1 = t_1_fu_220_p4;

assign zext_ln2122_fu_258_p1 = t_3_fu_248_p4;

assign zext_ln2130_1_fu_357_p1 = tab_q0;

assign zext_ln2130_fu_314_p1 = t_5_fu_306_p3;

assign zext_ln3157_fu_411_p1 = trunc_ln4_fu_401_p4;

always @ (posedge ap_clk) begin
    ap_return_preg[63:32] <= 32'b00000000000000000000000000000000;
end

endmodule //fixed_to_float_top_convert_ac_fixed_ac_float_25_2_8_0_s
