// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module add_float_top_adjust_9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        this_m_0_read,
        new_e_0,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [24:0] this_m_0_read;
input  [8:0] new_e_0;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ap_return_0;
reg[31:0] ap_return_1;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] tab_address0;
reg    tab_ce0;
wire   [2:0] tab_q0;
wire   [0:0] tmp_16_fu_224_p3;
reg   [0:0] tmp_16_reg_975;
wire   [0:0] cmp1_i_i_fu_248_p2;
reg   [0:0] cmp1_i_i_reg_979;
reg   [8:0] max_shift_reg_984;
wire   [24:0] select_ln609_fu_529_p3;
wire   [0:0] icmp_ln2118_fu_574_p2;
reg   [0:0] icmp_ln2118_reg_996;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln2122_fu_606_p2;
reg   [0:0] icmp_ln2122_reg_1002;
wire   [0:0] icmp_ln2126_fu_630_p2;
reg   [0:0] icmp_ln2126_reg_1007;
wire    grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_start;
wire    grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_done;
wire    grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_idle;
wire    grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_ready;
wire   [31:0] grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_k_out;
wire    grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_k_out_ap_vld;
reg   [7:0] ap_phi_mux_this_e_0_1_phi_fu_165_p6;
reg   [7:0] this_e_0_1_reg_161;
wire   [7:0] xor_ln609_fu_932_p2;
wire    ap_CS_fsm_state3;
wire   [0:0] or_ln543_fu_905_p2;
reg   [24:0] ap_phi_mux_this_m_0_1_phi_fu_178_p6;
reg   [24:0] this_m_0_1_reg_175;
wire   [24:0] select_ln609_1_fu_858_p3;
wire   [24:0] select_ln548_fu_919_p3;
reg    grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_start_reg;
wire   [63:0] zext_ln2130_fu_658_p1;
wire  signed [24:0] this_m_0_read_cast_fu_192_p0;
wire  signed [8:0] sext_ln609_fu_196_p0;
wire  signed [8:0] shl_ln_fu_200_p1;
wire  signed [30:0] shl_ln_fu_200_p3;
wire  signed [31:0] sext_ln609_1_fu_208_p1;
wire   [31:0] add_ln609_fu_212_p2;
wire  signed [24:0] ext_sign_fu_232_p1;
wire   [0:0] ext_sign_fu_232_p3;
wire   [24:0] select_ln2137_fu_240_p3;
wire  signed [24:0] cmp1_i_i_fu_248_p1;
wire   [30:0] add_ln1123_fu_218_p2;
wire  signed [9:0] sext_ln609_fu_196_p1;
wire   [9:0] value_fu_265_p2;
wire   [9:0] sub_ln1845_fu_283_p2;
wire   [3:0] tmp_19_fu_301_p4;
wire   [0:0] icmp_ln1795_fu_311_p2;
wire   [0:0] tmp_18_fu_293_p3;
wire   [4:0] s31_fu_289_p1;
wire   [0:0] ishift_fu_317_p2;
wire   [4:0] s31_2_fu_271_p1;
wire   [3:0] tmp_21_fu_351_p4;
wire   [0:0] icmp_ln1815_fu_361_p2;
wire   [0:0] tmp_20_fu_343_p3;
wire  signed [24:0] ext_fu_373_p1;
wire   [0:0] ext_fu_373_p3;
wire  signed [24:0] shl_ln1799_fu_407_p0;
wire   [24:0] s31cast_fu_403_p1;
wire  signed [24:0] select_ln1807_1_fu_413_p2;
wire   [5:0] zext_ln1814_1_fu_339_p1;
wire   [5:0] sub_i_i_i_i_fu_421_p2;
wire  signed [31:0] this_m_0_read_cast_fu_192_p1;
wire   [31:0] zext_ln1814_fu_335_p1;
wire   [31:0] lshr_ln1820_fu_431_p2;
wire   [31:0] select_ln1816_fu_381_p3;
wire   [31:0] zext_ln1820_fu_427_p1;
wire   [31:0] shl_ln1820_fu_441_p2;
wire   [24:0] trunc_ln1820_2_fu_447_p1;
wire   [24:0] trunc_ln1820_fu_437_p1;
wire   [0:0] ishift_2_fu_367_p2;
wire   [24:0] select_ln1816_2_fu_389_p3;
wire  signed [24:0] select_ln1828_fu_457_p2;
wire   [0:0] tmp_17_fu_275_p3;
wire   [0:0] or_ln1817_fu_465_p2;
wire   [0:0] icmp_ln1817_fu_397_p2;
wire   [0:0] xor_ln1817_fu_471_p2;
wire   [0:0] and_ln1817_fu_477_p2;
wire   [24:0] or_ln1820_fu_451_p2;
wire   [24:0] select_ln1828_fu_457_p3;
wire   [0:0] xor_ln1796_fu_329_p2;
wire   [0:0] and_ln1796_fu_491_p2;
wire   [0:0] icmp_ln1796_fu_323_p2;
wire   [0:0] and_ln1796_2_fu_497_p2;
wire   [24:0] shl_ln1799_fu_407_p2;
wire   [24:0] select_ln1817_fu_483_p3;
wire   [0:0] xor_ln1796_1_fu_511_p2;
wire   [0:0] or_ln1796_fu_517_p2;
wire   [0:0] and_ln1796_3_fu_523_p2;
wire   [24:0] select_ln1807_1_fu_413_p3;
wire   [24:0] select_ln1796_fu_503_p3;
wire  signed [24:0] bit_fu_537_p1;
wire  signed [24:0] xor_ln2116_fu_544_p0;
wire   [0:0] bit_fu_537_p3;
wire   [24:0] xor_ln2116_fu_544_p2;
wire  signed [24:0] t_fu_549_p2;
wire   [24:0] t_fu_549_p3;
wire  signed [8:0] trunc_ln_fu_556_p4;
wire  signed [15:0] sext_ln2118_fu_566_p1;
wire   [24:0] zext_ln2118_fu_570_p1;
wire   [24:0] t_1_fu_580_p3;
wire  signed [16:0] trunc_ln1_fu_588_p4;
wire  signed [23:0] sext_ln2122_fu_598_p1;
wire   [24:0] zext_ln2122_fu_602_p1;
wire   [24:0] t_2_fu_612_p3;
wire   [20:0] trunc_ln2_fu_620_p4;
wire   [3:0] tmp_fu_636_p4;
wire   [3:0] trunc_ln2126_fu_646_p1;
wire   [3:0] t_3_fu_650_p3;
wire   [4:0] select_ln2118_1_fu_674_p3;
wire   [4:0] select_ln2125_fu_681_p3;
wire   [4:0] select_ln2122_1_fu_688_p3;
wire   [4:0] or_ln2126_fu_695_p2;
wire   [4:0] zext_ln2130_1_fu_708_p1;
wire   [4:0] select_ln2126_1_fu_701_p3;
wire   [4:0] add_ln2142_1_fu_712_p2;
wire   [31:0] shl_ln1_fu_718_p3;
wire   [31:0] add_ln2142_fu_726_p2;
wire   [0:0] tmp_25_fu_666_p3;
wire   [4:0] trunc_ln2142_1_fu_732_p4;
wire   [4:0] lshift_fu_742_p3;
wire   [8:0] zext_ln3157_fu_750_p1;
wire   [0:0] icmp_ln3162_fu_754_p2;
wire   [8:0] lshift_2_fu_764_p3;
wire  signed [24:0] retval_fu_775_p0;
wire   [0:0] retval_fu_775_p2;
wire   [0:0] or_ln3172_fu_780_p2;
wire   [8:0] expt_fu_759_p2;
wire   [2:0] tmp_27_fu_802_p4;
wire   [0:0] icmp_ln1795_1_fu_812_p2;
wire   [0:0] tmp_26_fu_794_p3;
wire   [4:0] s31_3_fu_771_p1;
wire   [0:0] ishift_3_fu_818_p2;
wire   [0:0] icmp_ln1796_2_fu_824_p2;
wire   [0:0] xor_ln1796_2_fu_830_p2;
wire  signed [24:0] shl_ln1799_1_fu_846_p0;
wire   [24:0] s31_3cast_fu_842_p1;
wire  signed [24:0] select_ln1807_fu_851_p2;
wire   [0:0] and_ln1796_1_fu_836_p2;
wire   [24:0] shl_ln1799_1_fu_846_p2;
wire   [24:0] select_ln1807_fu_851_p3;
wire   [8:0] expt_1_fu_786_p3;
wire   [31:0] shl_ln609_1_fu_867_p3;
wire   [31:0] add_ln609_1_fu_875_p2;
wire   [1:0] tmp_29_fu_889_p4;
wire   [0:0] tmp_28_fu_881_p3;
wire   [0:0] retval_2_fu_899_p2;
wire   [0:0] tmp_30_fu_911_p3;
wire   [7:0] trunc_ln609_fu_928_p1;
wire  signed [31:0] sext_ln554_1_fu_943_p1;
wire  signed [31:0] sext_ln554_fu_939_p1;
reg   [31:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_start_reg = 1'b0;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 32'd0;
end

add_float_top_adjust_9_s_tab_ROM_AUTO_1R #(
    .DataWidth( 3 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
tab_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tab_address0),
    .ce0(tab_ce0),
    .q0(tab_q0)
);

add_float_top_adjust_9_Pipeline_VITIS_LOOP_2139_1 grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_start),
    .ap_done(grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_done),
    .ap_idle(grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_idle),
    .ap_ready(grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_ready),
    .cmp1_i_i(cmp1_i_i_reg_979),
    .k_out(grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_k_out),
    .k_out_ap_vld(grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_k_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_return_0_preg <= sext_ln554_1_fu_943_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 32'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_return_1_preg <= sext_ln554_fu_939_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (tmp_16_fu_224_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_start_reg <= 1'b1;
        end else if ((grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_ready == 1'b1)) begin
            grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln543_fu_905_p2 == 1'd0) & (tmp_16_reg_975 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        this_e_0_1_reg_161 <= 8'd127;
    end else if (((or_ln543_fu_905_p2 == 1'd1) & (tmp_16_reg_975 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        this_e_0_1_reg_161 <= xor_ln609_fu_932_p2;
    end else if (((ap_start == 1'b1) & (tmp_16_fu_224_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        this_e_0_1_reg_161 <= 8'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln543_fu_905_p2 == 1'd0) & (tmp_16_reg_975 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        this_m_0_1_reg_175 <= select_ln548_fu_919_p3;
    end else if (((or_ln543_fu_905_p2 == 1'd1) & (tmp_16_reg_975 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        this_m_0_1_reg_175 <= select_ln609_1_fu_858_p3;
    end else if (((ap_start == 1'b1) & (tmp_16_fu_224_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        this_m_0_1_reg_175 <= select_ln609_fu_529_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_16_fu_224_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        cmp1_i_i_reg_979 <= cmp1_i_i_fu_248_p2;
        max_shift_reg_984 <= {{add_ln1123_fu_218_p2[30:22]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln2118_reg_996 <= icmp_ln2118_fu_574_p2;
        icmp_ln2122_reg_1002 <= icmp_ln2122_fu_606_p2;
        icmp_ln2126_reg_1007 <= icmp_ln2126_fu_630_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_16_reg_975 <= add_ln609_fu_212_p2[32'd31];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_16_reg_975 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        if ((or_ln543_fu_905_p2 == 1'd0)) begin
            ap_phi_mux_this_e_0_1_phi_fu_165_p6 = 8'd127;
        end else if ((or_ln543_fu_905_p2 == 1'd1)) begin
            ap_phi_mux_this_e_0_1_phi_fu_165_p6 = xor_ln609_fu_932_p2;
        end else begin
            ap_phi_mux_this_e_0_1_phi_fu_165_p6 = this_e_0_1_reg_161;
        end
    end else begin
        ap_phi_mux_this_e_0_1_phi_fu_165_p6 = this_e_0_1_reg_161;
    end
end

always @ (*) begin
    if (((tmp_16_reg_975 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        if ((or_ln543_fu_905_p2 == 1'd0)) begin
            ap_phi_mux_this_m_0_1_phi_fu_178_p6 = select_ln548_fu_919_p3;
        end else if ((or_ln543_fu_905_p2 == 1'd1)) begin
            ap_phi_mux_this_m_0_1_phi_fu_178_p6 = select_ln609_1_fu_858_p3;
        end else begin
            ap_phi_mux_this_m_0_1_phi_fu_178_p6 = this_m_0_1_reg_175;
        end
    end else begin
        ap_phi_mux_this_m_0_1_phi_fu_178_p6 = this_m_0_1_reg_175;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_return_0 = sext_ln554_1_fu_943_p1;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_return_1 = sext_ln554_fu_939_p1;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        tab_ce0 = 1'b1;
    end else begin
        tab_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (tmp_16_fu_224_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((ap_start == 1'b1) & (tmp_16_fu_224_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1123_fu_218_p2 = ($signed(shl_ln_fu_200_p3) + $signed(31'd536870912));

assign add_ln2142_1_fu_712_p2 = (zext_ln2130_1_fu_708_p1 + select_ln2126_1_fu_701_p3);

assign add_ln2142_fu_726_p2 = ($signed(shl_ln1_fu_718_p3) + $signed(32'd3221225472));

assign add_ln609_1_fu_875_p2 = ($signed(shl_ln609_1_fu_867_p3) + $signed(32'd3221225472));

assign add_ln609_fu_212_p2 = ($signed(sext_ln609_1_fu_208_p1) + $signed(32'd536870912));

assign and_ln1796_1_fu_836_p2 = (xor_ln1796_2_fu_830_p2 & icmp_ln1796_2_fu_824_p2);

assign and_ln1796_2_fu_497_p2 = (icmp_ln1796_fu_323_p2 & and_ln1796_fu_491_p2);

assign and_ln1796_3_fu_523_p2 = (tmp_17_fu_275_p3 & or_ln1796_fu_517_p2);

assign and_ln1796_fu_491_p2 = (xor_ln1796_fu_329_p2 & tmp_17_fu_275_p3);

assign and_ln1817_fu_477_p2 = (xor_ln1817_fu_471_p2 & icmp_ln1817_fu_397_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign bit_fu_537_p1 = this_m_0_read;

assign bit_fu_537_p3 = bit_fu_537_p1[32'd24];

assign cmp1_i_i_fu_248_p1 = this_m_0_read;

assign cmp1_i_i_fu_248_p2 = ((select_ln2137_fu_240_p3 == cmp1_i_i_fu_248_p1) ? 1'b1 : 1'b0);

assign expt_1_fu_786_p3 = ((or_ln3172_fu_780_p2[0:0] == 1'b1) ? 9'd0 : expt_fu_759_p2);

assign expt_fu_759_p2 = (max_shift_reg_984 - zext_ln3157_fu_750_p1);

assign ext_fu_373_p1 = this_m_0_read;

assign ext_fu_373_p3 = ext_fu_373_p1[32'd24];

assign ext_sign_fu_232_p1 = this_m_0_read;

assign ext_sign_fu_232_p3 = ext_sign_fu_232_p1[32'd24];

assign grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_start = grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_ap_start_reg;

assign icmp_ln1795_1_fu_812_p2 = ((tmp_27_fu_802_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1795_fu_311_p2 = ((tmp_19_fu_301_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln1796_2_fu_824_p2 = ((s31_3_fu_771_p1 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1796_fu_323_p2 = ((s31_fu_289_p1 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln1815_fu_361_p2 = ((tmp_21_fu_351_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln1817_fu_397_p2 = ((s31_2_fu_271_p1 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln2118_fu_574_p2 = ((trunc_ln_fu_556_p4 != 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln2122_fu_606_p2 = ((trunc_ln1_fu_588_p4 != 17'd0) ? 1'b1 : 1'b0);

assign icmp_ln2126_fu_630_p2 = ((trunc_ln2_fu_620_p4 != 21'd0) ? 1'b1 : 1'b0);

assign icmp_ln3162_fu_754_p2 = ((zext_ln3157_fu_750_p1 > max_shift_reg_984) ? 1'b1 : 1'b0);

assign ishift_2_fu_367_p2 = (tmp_20_fu_343_p3 | icmp_ln1815_fu_361_p2);

assign ishift_3_fu_818_p2 = (tmp_26_fu_794_p3 | icmp_ln1795_1_fu_812_p2);

assign ishift_fu_317_p2 = (tmp_18_fu_293_p3 | icmp_ln1795_fu_311_p2);

assign lshift_2_fu_764_p3 = ((icmp_ln3162_fu_754_p2[0:0] == 1'b1) ? max_shift_reg_984 : zext_ln3157_fu_750_p1);

assign lshift_fu_742_p3 = ((tmp_25_fu_666_p3[0:0] == 1'b1) ? 5'd24 : trunc_ln2142_1_fu_732_p4);

assign lshr_ln1820_fu_431_p2 = this_m_0_read_cast_fu_192_p1 >> zext_ln1814_fu_335_p1;

assign or_ln1796_fu_517_p2 = (xor_ln1796_1_fu_511_p2 | ishift_fu_317_p2);

assign or_ln1817_fu_465_p2 = (tmp_17_fu_275_p3 | ishift_2_fu_367_p2);

assign or_ln1820_fu_451_p2 = (trunc_ln1820_fu_437_p1 | trunc_ln1820_2_fu_447_p1);

assign or_ln2126_fu_695_p2 = (select_ln2122_1_fu_688_p3 | 5'd4);

assign or_ln3172_fu_780_p2 = (retval_fu_775_p2 | icmp_ln3162_fu_754_p2);

assign or_ln543_fu_905_p2 = (tmp_28_fu_881_p3 | retval_2_fu_899_p2);

assign retval_2_fu_899_p2 = ((tmp_29_fu_889_p4 == 2'd0) ? 1'b1 : 1'b0);

assign retval_fu_775_p0 = this_m_0_read;

assign retval_fu_775_p2 = ((retval_fu_775_p0 == 25'd0) ? 1'b1 : 1'b0);

assign s31_2_fu_271_p1 = value_fu_265_p2[4:0];

assign s31_3_fu_771_p1 = lshift_2_fu_764_p3[4:0];

assign s31_3cast_fu_842_p1 = s31_3_fu_771_p1;

assign s31_fu_289_p1 = sub_ln1845_fu_283_p2[4:0];

assign s31cast_fu_403_p1 = s31_fu_289_p1;

assign select_ln1796_fu_503_p3 = ((and_ln1796_2_fu_497_p2[0:0] == 1'b1) ? shl_ln1799_fu_407_p2 : select_ln1817_fu_483_p3);

assign select_ln1807_1_fu_413_p2 = this_m_0_read;

assign select_ln1807_1_fu_413_p3 = ((ishift_fu_317_p2[0:0] == 1'b1) ? 25'd0 : select_ln1807_1_fu_413_p2);

assign select_ln1807_fu_851_p2 = this_m_0_read;

assign select_ln1807_fu_851_p3 = ((ishift_3_fu_818_p2[0:0] == 1'b1) ? 25'd0 : select_ln1807_fu_851_p2);

assign select_ln1816_2_fu_389_p3 = ((ext_fu_373_p3[0:0] == 1'b1) ? 25'd33554431 : 25'd0);

assign select_ln1816_fu_381_p3 = ((ext_fu_373_p3[0:0] == 1'b1) ? 32'd4294967295 : 32'd0);

assign select_ln1817_fu_483_p3 = ((and_ln1817_fu_477_p2[0:0] == 1'b1) ? or_ln1820_fu_451_p2 : select_ln1828_fu_457_p3);

assign select_ln1828_fu_457_p2 = this_m_0_read;

assign select_ln1828_fu_457_p3 = ((ishift_2_fu_367_p2[0:0] == 1'b1) ? select_ln1816_2_fu_389_p3 : select_ln1828_fu_457_p2);

assign select_ln2118_1_fu_674_p3 = ((icmp_ln2118_reg_996[0:0] == 1'b1) ? 5'd0 : 5'd16);

assign select_ln2122_1_fu_688_p3 = ((icmp_ln2122_reg_1002[0:0] == 1'b1) ? select_ln2118_1_fu_674_p3 : select_ln2125_fu_681_p3);

assign select_ln2125_fu_681_p3 = ((icmp_ln2118_reg_996[0:0] == 1'b1) ? 5'd8 : 5'd24);

assign select_ln2126_1_fu_701_p3 = ((icmp_ln2126_reg_1007[0:0] == 1'b1) ? select_ln2122_1_fu_688_p3 : or_ln2126_fu_695_p2);

assign select_ln2137_fu_240_p3 = ((ext_sign_fu_232_p3[0:0] == 1'b1) ? 25'd33554431 : 25'd0);

assign select_ln548_fu_919_p3 = ((tmp_30_fu_911_p3[0:0] == 1'b1) ? 25'd16777216 : 25'd16777215);

assign select_ln609_1_fu_858_p3 = ((and_ln1796_1_fu_836_p2[0:0] == 1'b1) ? shl_ln1799_1_fu_846_p2 : select_ln1807_fu_851_p3);

assign select_ln609_fu_529_p3 = ((and_ln1796_3_fu_523_p2[0:0] == 1'b1) ? select_ln1807_1_fu_413_p3 : select_ln1796_fu_503_p3);

assign sext_ln2118_fu_566_p1 = trunc_ln_fu_556_p4;

assign sext_ln2122_fu_598_p1 = trunc_ln1_fu_588_p4;

assign sext_ln554_1_fu_943_p1 = $signed(ap_phi_mux_this_e_0_1_phi_fu_165_p6);

assign sext_ln554_fu_939_p1 = $signed(ap_phi_mux_this_m_0_1_phi_fu_178_p6);

assign sext_ln609_1_fu_208_p1 = shl_ln_fu_200_p3;

assign sext_ln609_fu_196_p0 = new_e_0;

assign sext_ln609_fu_196_p1 = sext_ln609_fu_196_p0;

assign shl_ln1799_1_fu_846_p0 = this_m_0_read;

assign shl_ln1799_1_fu_846_p2 = shl_ln1799_1_fu_846_p0 << s31_3cast_fu_842_p1;

assign shl_ln1799_fu_407_p0 = this_m_0_read;

assign shl_ln1799_fu_407_p2 = shl_ln1799_fu_407_p0 << s31cast_fu_403_p1;

assign shl_ln1820_fu_441_p2 = select_ln1816_fu_381_p3 << zext_ln1820_fu_427_p1;

assign shl_ln1_fu_718_p3 = {{add_ln2142_1_fu_712_p2}, {27'd0}};

assign shl_ln609_1_fu_867_p3 = {{expt_1_fu_786_p3}, {23'd0}};

assign shl_ln_fu_200_p1 = new_e_0;

assign shl_ln_fu_200_p3 = {{shl_ln_fu_200_p1}, {22'd0}};

assign sub_i_i_i_i_fu_421_p2 = ($signed(6'd32) - $signed(zext_ln1814_1_fu_339_p1));

assign sub_ln1845_fu_283_p2 = (10'd0 - value_fu_265_p2);

assign t_1_fu_580_p3 = ((icmp_ln2118_fu_574_p2[0:0] == 1'b1) ? zext_ln2118_fu_570_p1 : t_fu_549_p3);

assign t_2_fu_612_p3 = ((icmp_ln2122_fu_606_p2[0:0] == 1'b1) ? zext_ln2122_fu_602_p1 : t_1_fu_580_p3);

assign t_3_fu_650_p3 = ((icmp_ln2126_fu_630_p2[0:0] == 1'b1) ? tmp_fu_636_p4 : trunc_ln2126_fu_646_p1);

assign t_fu_549_p2 = this_m_0_read;

assign t_fu_549_p3 = ((bit_fu_537_p3[0:0] == 1'b1) ? xor_ln2116_fu_544_p2 : t_fu_549_p2);

assign tab_address0 = zext_ln2130_fu_658_p1;

assign this_m_0_read_cast_fu_192_p0 = this_m_0_read;

assign this_m_0_read_cast_fu_192_p1 = this_m_0_read_cast_fu_192_p0;

assign tmp_16_fu_224_p3 = add_ln609_fu_212_p2[32'd31];

assign tmp_17_fu_275_p3 = value_fu_265_p2[32'd9];

assign tmp_18_fu_293_p3 = sub_ln1845_fu_283_p2[32'd5];

assign tmp_19_fu_301_p4 = {{sub_ln1845_fu_283_p2[9:6]}};

assign tmp_20_fu_343_p3 = value_fu_265_p2[32'd5];

assign tmp_21_fu_351_p4 = {{value_fu_265_p2[9:6]}};

assign tmp_25_fu_666_p3 = grp_adjust_9_Pipeline_VITIS_LOOP_2139_1_fu_186_k_out[32'd31];

assign tmp_26_fu_794_p3 = lshift_2_fu_764_p3[32'd5];

assign tmp_27_fu_802_p4 = {{lshift_2_fu_764_p3[8:6]}};

assign tmp_28_fu_881_p3 = add_ln609_1_fu_875_p2[32'd31];

assign tmp_29_fu_889_p4 = {{add_ln609_1_fu_875_p2[31:30]}};

assign tmp_30_fu_911_p3 = select_ln609_1_fu_858_p3[32'd24];

assign tmp_fu_636_p4 = {{t_2_fu_612_p3[7:4]}};

assign trunc_ln1820_2_fu_447_p1 = shl_ln1820_fu_441_p2[24:0];

assign trunc_ln1820_fu_437_p1 = lshr_ln1820_fu_431_p2[24:0];

assign trunc_ln1_fu_588_p4 = {{t_1_fu_580_p3[24:8]}};

assign trunc_ln2126_fu_646_p1 = t_2_fu_612_p3[3:0];

assign trunc_ln2142_1_fu_732_p4 = {{add_ln2142_fu_726_p2[31:27]}};

assign trunc_ln2_fu_620_p4 = {{t_2_fu_612_p3[24:4]}};

assign trunc_ln609_fu_928_p1 = expt_1_fu_786_p3[7:0];

assign trunc_ln_fu_556_p4 = {{t_fu_549_p3[24:16]}};

assign value_fu_265_p2 = ($signed(10'd896) - $signed(sext_ln609_fu_196_p1));

assign xor_ln1796_1_fu_511_p2 = (icmp_ln1796_fu_323_p2 ^ 1'd1);

assign xor_ln1796_2_fu_830_p2 = (ishift_3_fu_818_p2 ^ 1'd1);

assign xor_ln1796_fu_329_p2 = (ishift_fu_317_p2 ^ 1'd1);

assign xor_ln1817_fu_471_p2 = (or_ln1817_fu_465_p2 ^ 1'd1);

assign xor_ln2116_fu_544_p0 = this_m_0_read;

assign xor_ln2116_fu_544_p2 = (xor_ln2116_fu_544_p0 ^ 25'd33554431);

assign xor_ln609_fu_932_p2 = (trunc_ln609_fu_928_p1 ^ 8'd128);

assign zext_ln1814_1_fu_339_p1 = s31_2_fu_271_p1;

assign zext_ln1814_fu_335_p1 = s31_2_fu_271_p1;

assign zext_ln1820_fu_427_p1 = sub_i_i_i_i_fu_421_p2;

assign zext_ln2118_fu_570_p1 = $unsigned(sext_ln2118_fu_566_p1);

assign zext_ln2122_fu_602_p1 = $unsigned(sext_ln2122_fu_598_p1);

assign zext_ln2130_1_fu_708_p1 = tab_q0;

assign zext_ln2130_fu_658_p1 = t_3_fu_650_p3;

assign zext_ln3157_fu_750_p1 = lshift_fu_742_p3;

endmodule //add_float_top_adjust_9_s
