// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module add_float_top_set (
        ap_ready,
        this_v_read,
        x,
        value_r,
        ap_return
);


output   ap_ready;
input  [63:0] this_v_read;
input  [0:0] x;
input  [31:0] value_r;
output  [63:0] ap_return;

wire   [31:0] tmp_fu_42_p4;
wire   [31:0] empty_fu_38_p1;
wire   [63:0] or_ln1_fu_60_p3;
wire   [63:0] or_ln_fu_52_p3;

assign ap_ready = 1'b1;

assign empty_fu_38_p1 = this_v_read[31:0];

assign or_ln1_fu_60_p3 = {{value_r}, {empty_fu_38_p1}};

assign or_ln_fu_52_p3 = {{tmp_fu_42_p4}, {value_r}};

assign tmp_fu_42_p4 = {{this_v_read[63:32]}};

assign ap_return = ((x[0:0] == 1'b1) ? or_ln1_fu_60_p3 : or_ln_fu_52_p3);

endmodule //add_float_top_set
