// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="add_fixed_top_add_fixed_top,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=50.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=33.353750,HLS_SYN_LAT=1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=309,HLS_SYN_LUT=1053,HLS_VERSION=2022_2}" *)

module add_fixed_top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        b,
        res,
        res_ap_vld
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [319:0] a;
input  [319:0] b;
output  [319:0] res;
output   res_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg res_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] add_ln1334_fu_247_p2;
reg   [31:0] add_ln1334_reg_653;
wire   [31:0] add_ln1334_4_fu_295_p2;
reg   [31:0] add_ln1334_4_reg_658;
wire   [31:0] add_ln1334_8_fu_343_p2;
reg   [31:0] add_ln1334_8_reg_663;
wire   [31:0] add_ln1334_12_fu_391_p2;
reg   [31:0] add_ln1334_12_reg_668;
wire   [31:0] add_ln1334_16_fu_439_p2;
reg   [31:0] add_ln1334_16_reg_673;
wire   [31:0] add_ln1334_20_fu_487_p2;
reg   [31:0] add_ln1334_20_reg_678;
wire   [31:0] add_ln1334_24_fu_535_p2;
reg   [31:0] add_ln1334_24_reg_683;
wire   [31:0] add_ln1334_28_fu_583_p2;
reg   [31:0] add_ln1334_28_reg_688;
reg   [0:0] tmp_reg_693;
reg   [24:0] trunc_ln1309_1_reg_698;
reg   [24:0] trunc_ln1309_2_reg_703;
wire    ap_CS_fsm_state2;
wire   [31:0] trunc_ln1356_fu_85_p1;
wire   [31:0] trunc_ln1358_fu_159_p1;
wire   [32:0] zext_ln1334_1_fu_237_p1;
wire   [32:0] zext_ln1334_fu_233_p1;
wire   [32:0] l_fu_241_p2;
wire   [0:0] l_1_fu_253_p3;
wire   [31:0] trunc_ln1356_1_fu_89_p4;
wire   [31:0] trunc_ln1358_1_fu_163_p4;
wire   [32:0] zext_ln1334_3_fu_269_p1;
wire   [32:0] zext_ln1334_2_fu_265_p1;
wire   [32:0] add_ln1334_2_fu_277_p2;
wire   [32:0] zext_ln1334_16_fu_261_p1;
wire   [31:0] zext_ln1334_17_fu_273_p1;
wire   [31:0] add_ln1334_5_fu_289_p2;
wire   [32:0] l_2_fu_283_p2;
wire   [0:0] l_3_fu_301_p3;
wire   [31:0] trunc_ln1356_2_fu_99_p4;
wire   [31:0] trunc_ln1358_2_fu_173_p4;
wire   [32:0] zext_ln1334_5_fu_317_p1;
wire   [32:0] zext_ln1334_4_fu_313_p1;
wire   [32:0] add_ln1334_6_fu_325_p2;
wire   [32:0] zext_ln1334_18_fu_309_p1;
wire   [31:0] zext_ln1334_19_fu_321_p1;
wire   [31:0] add_ln1334_9_fu_337_p2;
wire   [32:0] l_4_fu_331_p2;
wire   [0:0] l_5_fu_349_p3;
wire   [31:0] trunc_ln1356_3_fu_109_p4;
wire   [31:0] trunc_ln1358_3_fu_183_p4;
wire   [32:0] zext_ln1334_7_fu_365_p1;
wire   [32:0] zext_ln1334_6_fu_361_p1;
wire   [32:0] add_ln1334_10_fu_373_p2;
wire   [32:0] zext_ln1334_20_fu_357_p1;
wire   [31:0] zext_ln1334_21_fu_369_p1;
wire   [31:0] add_ln1334_13_fu_385_p2;
wire   [32:0] l_6_fu_379_p2;
wire   [0:0] l_7_fu_397_p3;
wire   [31:0] trunc_ln1356_4_fu_119_p4;
wire   [31:0] trunc_ln1358_4_fu_193_p4;
wire   [32:0] zext_ln1334_9_fu_413_p1;
wire   [32:0] zext_ln1334_8_fu_409_p1;
wire   [32:0] add_ln1334_14_fu_421_p2;
wire   [32:0] zext_ln1334_22_fu_405_p1;
wire   [31:0] zext_ln1334_23_fu_417_p1;
wire   [31:0] add_ln1334_17_fu_433_p2;
wire   [32:0] l_8_fu_427_p2;
wire   [0:0] l_9_fu_445_p3;
wire   [31:0] trunc_ln1356_5_fu_129_p4;
wire   [31:0] trunc_ln1358_5_fu_203_p4;
wire   [32:0] zext_ln1334_11_fu_461_p1;
wire   [32:0] zext_ln1334_10_fu_457_p1;
wire   [32:0] add_ln1334_18_fu_469_p2;
wire   [32:0] zext_ln1334_24_fu_453_p1;
wire   [31:0] zext_ln1334_25_fu_465_p1;
wire   [31:0] add_ln1334_21_fu_481_p2;
wire   [32:0] l_10_fu_475_p2;
wire   [0:0] l_11_fu_493_p3;
wire   [31:0] trunc_ln1356_6_fu_139_p4;
wire   [31:0] trunc_ln1358_6_fu_213_p4;
wire   [32:0] zext_ln1334_13_fu_509_p1;
wire   [32:0] zext_ln1334_12_fu_505_p1;
wire   [32:0] add_ln1334_22_fu_517_p2;
wire   [32:0] zext_ln1334_26_fu_501_p1;
wire   [31:0] zext_ln1334_27_fu_513_p1;
wire   [31:0] add_ln1334_25_fu_529_p2;
wire   [32:0] l_12_fu_523_p2;
wire   [0:0] l_13_fu_541_p3;
wire   [31:0] trunc_ln1356_7_fu_149_p4;
wire   [31:0] trunc_ln1358_7_fu_223_p4;
wire   [32:0] zext_ln1334_15_fu_557_p1;
wire   [32:0] zext_ln1334_14_fu_553_p1;
wire   [32:0] add_ln1334_26_fu_565_p2;
wire   [32:0] zext_ln1334_28_fu_549_p1;
wire   [31:0] zext_ln1334_29_fu_561_p1;
wire   [31:0] add_ln1334_29_fu_577_p2;
wire   [32:0] l_14_fu_571_p2;
wire   [24:0] zext_ln479_fu_617_p1;
wire   [24:0] add_ln479_1_fu_620_p2;
wire   [24:0] add_ln479_fu_625_p2;
wire   [280:0] tmp_i_fu_630_p10;
wire  signed [287:0] sext_ln6_fu_644_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln1334_12_reg_668 <= add_ln1334_12_fu_391_p2;
        add_ln1334_16_reg_673 <= add_ln1334_16_fu_439_p2;
        add_ln1334_20_reg_678 <= add_ln1334_20_fu_487_p2;
        add_ln1334_24_reg_683 <= add_ln1334_24_fu_535_p2;
        add_ln1334_28_reg_688 <= add_ln1334_28_fu_583_p2;
        add_ln1334_4_reg_658 <= add_ln1334_4_fu_295_p2;
        add_ln1334_8_reg_663 <= add_ln1334_8_fu_343_p2;
        add_ln1334_reg_653 <= add_ln1334_fu_247_p2;
        tmp_reg_693 <= l_14_fu_571_p2[32'd32];
        trunc_ln1309_1_reg_698 <= {{a[280:256]}};
        trunc_ln1309_2_reg_703 <= {{b[280:256]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        res_ap_vld = 1'b1;
    end else begin
        res_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1334_10_fu_373_p2 = (zext_ln1334_7_fu_365_p1 + zext_ln1334_6_fu_361_p1);

assign add_ln1334_12_fu_391_p2 = (add_ln1334_13_fu_385_p2 + trunc_ln1358_3_fu_183_p4);

assign add_ln1334_13_fu_385_p2 = (trunc_ln1356_3_fu_109_p4 + zext_ln1334_21_fu_369_p1);

assign add_ln1334_14_fu_421_p2 = (zext_ln1334_9_fu_413_p1 + zext_ln1334_8_fu_409_p1);

assign add_ln1334_16_fu_439_p2 = (add_ln1334_17_fu_433_p2 + trunc_ln1358_4_fu_193_p4);

assign add_ln1334_17_fu_433_p2 = (trunc_ln1356_4_fu_119_p4 + zext_ln1334_23_fu_417_p1);

assign add_ln1334_18_fu_469_p2 = (zext_ln1334_11_fu_461_p1 + zext_ln1334_10_fu_457_p1);

assign add_ln1334_20_fu_487_p2 = (add_ln1334_21_fu_481_p2 + trunc_ln1358_5_fu_203_p4);

assign add_ln1334_21_fu_481_p2 = (trunc_ln1356_5_fu_129_p4 + zext_ln1334_25_fu_465_p1);

assign add_ln1334_22_fu_517_p2 = (zext_ln1334_13_fu_509_p1 + zext_ln1334_12_fu_505_p1);

assign add_ln1334_24_fu_535_p2 = (add_ln1334_25_fu_529_p2 + trunc_ln1358_6_fu_213_p4);

assign add_ln1334_25_fu_529_p2 = (trunc_ln1356_6_fu_139_p4 + zext_ln1334_27_fu_513_p1);

assign add_ln1334_26_fu_565_p2 = (zext_ln1334_15_fu_557_p1 + zext_ln1334_14_fu_553_p1);

assign add_ln1334_28_fu_583_p2 = (add_ln1334_29_fu_577_p2 + trunc_ln1358_7_fu_223_p4);

assign add_ln1334_29_fu_577_p2 = (trunc_ln1356_7_fu_149_p4 + zext_ln1334_29_fu_561_p1);

assign add_ln1334_2_fu_277_p2 = (zext_ln1334_3_fu_269_p1 + zext_ln1334_2_fu_265_p1);

assign add_ln1334_4_fu_295_p2 = (add_ln1334_5_fu_289_p2 + trunc_ln1358_1_fu_163_p4);

assign add_ln1334_5_fu_289_p2 = (trunc_ln1356_1_fu_89_p4 + zext_ln1334_17_fu_273_p1);

assign add_ln1334_6_fu_325_p2 = (zext_ln1334_5_fu_317_p1 + zext_ln1334_4_fu_313_p1);

assign add_ln1334_8_fu_343_p2 = (add_ln1334_9_fu_337_p2 + trunc_ln1358_2_fu_173_p4);

assign add_ln1334_9_fu_337_p2 = (trunc_ln1356_2_fu_99_p4 + zext_ln1334_19_fu_321_p1);

assign add_ln1334_fu_247_p2 = (trunc_ln1358_fu_159_p1 + trunc_ln1356_fu_85_p1);

assign add_ln479_1_fu_620_p2 = (trunc_ln1309_1_reg_698 + zext_ln479_fu_617_p1);

assign add_ln479_fu_625_p2 = (add_ln479_1_fu_620_p2 + trunc_ln1309_2_reg_703);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign l_10_fu_475_p2 = (add_ln1334_18_fu_469_p2 + zext_ln1334_24_fu_453_p1);

assign l_11_fu_493_p3 = l_10_fu_475_p2[32'd32];

assign l_12_fu_523_p2 = (add_ln1334_22_fu_517_p2 + zext_ln1334_26_fu_501_p1);

assign l_13_fu_541_p3 = l_12_fu_523_p2[32'd32];

assign l_14_fu_571_p2 = (add_ln1334_26_fu_565_p2 + zext_ln1334_28_fu_549_p1);

assign l_1_fu_253_p3 = l_fu_241_p2[32'd32];

assign l_2_fu_283_p2 = (add_ln1334_2_fu_277_p2 + zext_ln1334_16_fu_261_p1);

assign l_3_fu_301_p3 = l_2_fu_283_p2[32'd32];

assign l_4_fu_331_p2 = (add_ln1334_6_fu_325_p2 + zext_ln1334_18_fu_309_p1);

assign l_5_fu_349_p3 = l_4_fu_331_p2[32'd32];

assign l_6_fu_379_p2 = (add_ln1334_10_fu_373_p2 + zext_ln1334_20_fu_357_p1);

assign l_7_fu_397_p3 = l_6_fu_379_p2[32'd32];

assign l_8_fu_427_p2 = (add_ln1334_14_fu_421_p2 + zext_ln1334_22_fu_405_p1);

assign l_9_fu_445_p3 = l_8_fu_427_p2[32'd32];

assign l_fu_241_p2 = (zext_ln1334_1_fu_237_p1 + zext_ln1334_fu_233_p1);

assign res = $unsigned(sext_ln6_fu_644_p1);

assign sext_ln6_fu_644_p1 = $signed(tmp_i_fu_630_p10);

assign tmp_i_fu_630_p10 = {{{{{{{{{add_ln479_fu_625_p2}, {add_ln1334_28_reg_688}}, {add_ln1334_24_reg_683}}, {add_ln1334_20_reg_678}}, {add_ln1334_16_reg_673}}, {add_ln1334_12_reg_668}}, {add_ln1334_8_reg_663}}, {add_ln1334_4_reg_658}}, {add_ln1334_reg_653}};

assign trunc_ln1356_1_fu_89_p4 = {{a[63:32]}};

assign trunc_ln1356_2_fu_99_p4 = {{a[95:64]}};

assign trunc_ln1356_3_fu_109_p4 = {{a[127:96]}};

assign trunc_ln1356_4_fu_119_p4 = {{a[159:128]}};

assign trunc_ln1356_5_fu_129_p4 = {{a[191:160]}};

assign trunc_ln1356_6_fu_139_p4 = {{a[223:192]}};

assign trunc_ln1356_7_fu_149_p4 = {{a[255:224]}};

assign trunc_ln1356_fu_85_p1 = a[31:0];

assign trunc_ln1358_1_fu_163_p4 = {{b[63:32]}};

assign trunc_ln1358_2_fu_173_p4 = {{b[95:64]}};

assign trunc_ln1358_3_fu_183_p4 = {{b[127:96]}};

assign trunc_ln1358_4_fu_193_p4 = {{b[159:128]}};

assign trunc_ln1358_5_fu_203_p4 = {{b[191:160]}};

assign trunc_ln1358_6_fu_213_p4 = {{b[223:192]}};

assign trunc_ln1358_7_fu_223_p4 = {{b[255:224]}};

assign trunc_ln1358_fu_159_p1 = b[31:0];

assign zext_ln1334_10_fu_457_p1 = trunc_ln1356_5_fu_129_p4;

assign zext_ln1334_11_fu_461_p1 = trunc_ln1358_5_fu_203_p4;

assign zext_ln1334_12_fu_505_p1 = trunc_ln1356_6_fu_139_p4;

assign zext_ln1334_13_fu_509_p1 = trunc_ln1358_6_fu_213_p4;

assign zext_ln1334_14_fu_553_p1 = trunc_ln1356_7_fu_149_p4;

assign zext_ln1334_15_fu_557_p1 = trunc_ln1358_7_fu_223_p4;

assign zext_ln1334_16_fu_261_p1 = l_1_fu_253_p3;

assign zext_ln1334_17_fu_273_p1 = l_1_fu_253_p3;

assign zext_ln1334_18_fu_309_p1 = l_3_fu_301_p3;

assign zext_ln1334_19_fu_321_p1 = l_3_fu_301_p3;

assign zext_ln1334_1_fu_237_p1 = trunc_ln1358_fu_159_p1;

assign zext_ln1334_20_fu_357_p1 = l_5_fu_349_p3;

assign zext_ln1334_21_fu_369_p1 = l_5_fu_349_p3;

assign zext_ln1334_22_fu_405_p1 = l_7_fu_397_p3;

assign zext_ln1334_23_fu_417_p1 = l_7_fu_397_p3;

assign zext_ln1334_24_fu_453_p1 = l_9_fu_445_p3;

assign zext_ln1334_25_fu_465_p1 = l_9_fu_445_p3;

assign zext_ln1334_26_fu_501_p1 = l_11_fu_493_p3;

assign zext_ln1334_27_fu_513_p1 = l_11_fu_493_p3;

assign zext_ln1334_28_fu_549_p1 = l_13_fu_541_p3;

assign zext_ln1334_29_fu_561_p1 = l_13_fu_541_p3;

assign zext_ln1334_2_fu_265_p1 = trunc_ln1356_1_fu_89_p4;

assign zext_ln1334_3_fu_269_p1 = trunc_ln1358_1_fu_163_p4;

assign zext_ln1334_4_fu_313_p1 = trunc_ln1356_2_fu_99_p4;

assign zext_ln1334_5_fu_317_p1 = trunc_ln1358_2_fu_173_p4;

assign zext_ln1334_6_fu_361_p1 = trunc_ln1356_3_fu_109_p4;

assign zext_ln1334_7_fu_365_p1 = trunc_ln1358_3_fu_183_p4;

assign zext_ln1334_8_fu_409_p1 = trunc_ln1356_4_fu_119_p4;

assign zext_ln1334_9_fu_413_p1 = trunc_ln1358_4_fu_193_p4;

assign zext_ln1334_fu_233_p1 = trunc_ln1356_fu_85_p1;

assign zext_ln479_fu_617_p1 = tmp_reg_693;

endmodule //add_fixed_top
