-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fixed_to_float_top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    fixpo : IN STD_LOGIC_VECTOR (63 downto 0);
    flopo : OUT STD_LOGIC_VECTOR (127 downto 0);
    flopo_ap_vld : OUT STD_LOGIC );
end;


architecture behav of fixed_to_float_top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fixed_to_float_top_fixed_to_float_top,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=50.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=21.346750,HLS_SYN_LAT=5,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=235,HLS_SYN_LUT=1063,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_start : STD_LOGIC;
    signal grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_done : STD_LOGIC;
    signal grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_idle : STD_LOGIC;
    signal grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_ready : STD_LOGIC;
    signal grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_return : STD_LOGIC_VECTOR (70 downto 0);
    signal grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sext_ln6_fu_49_p1 : STD_LOGIC_VECTOR (95 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fixed_to_float_top_convert_ac_fixed_ac_float_25_2_8_0_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        from_v_v_read : IN STD_LOGIC_VECTOR (63 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (70 downto 0) );
    end component;



begin
    grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41 : component fixed_to_float_top_convert_ac_fixed_ac_float_25_2_8_0_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_start,
        ap_done => grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_done,
        ap_idle => grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_idle,
        ap_ready => grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_ready,
        from_v_v_read => fixpo,
        ap_return => grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_ready = ap_const_logic_1)) then 
                    grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_done)
    begin
        if ((grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    flopo <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln6_fu_49_p1),128));

    flopo_ap_vld_assign_proc : process(grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            flopo_ap_vld <= ap_const_logic_1;
        else 
            flopo_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_start <= grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_start_reg;
        sext_ln6_fu_49_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_convert_ac_fixed_ac_float_25_2_8_0_s_fu_41_ap_return),96));

end behav;
